"""initial_schema

Revision ID: z_20260523185605
Revises: 
Create Date: 2026-05-23 18:56:05.906585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'z_20260523185605'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('lang', sa.String(length=5), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories'))
    )
    op.create_table('users',
    sa.Column('anonymous_id', sa.UUID(), nullable=False),
    sa.Column('last_visit', sa.Date(), nullable=True),
    sa.Column('streak_current', sa.Integer(), nullable=False),
    sa.Column('streak_longest', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('anonymous_id', name=op.f('uq_users_anonymous_id'))
    )
    op.create_table('topics',
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_topics_category_id_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_topics'))
    )
    op.create_table('subtopics',
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('subtitle', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_subtopics_topic_id_topics')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subtopics'))
    )
    op.create_table('exercises',
    sa.Column('subtopic_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('tag', sa.String(length=100), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('explanation_title', sa.Text(), nullable=False),
    sa.Column('explanation_body', sa.Text(), nullable=False),
    sa.Column('explanation_fact', sa.Text(), nullable=True),
    sa.Column('lang', sa.String(length=5), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subtopic_id'], ['subtopics.id'], name=op.f('fk_exercises_subtopic_id_subtopics')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exercises'))
    )
    op.create_table('sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('subtopic_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subtopic_id'], ['subtopics.id'], name=op.f('fk_sessions_subtopic_id_subtopics')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    op.create_table('answers',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('exercise_type', sa.String(length=30), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ms_to_answer', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('fk_answers_exercise_id_exercises')),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_answers_session_id_sessions')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_answers_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_answers'))
    )
    op.create_table('exercises_chrono_items',
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('item_key', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=300), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('fk_exercises_chrono_items_exercise_id_exercises')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exercises_chrono_items'))
    )
    op.create_table('exercises_estimation',
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('min_val', sa.Float(), nullable=False),
    sa.Column('max_val', sa.Float(), nullable=False),
    sa.Column('step', sa.Float(), nullable=False),
    sa.Column('default_value', sa.Float(), nullable=False),
    sa.Column('correct', sa.Float(), nullable=False),
    sa.Column('tolerance', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('fk_exercises_estimation_exercise_id_exercises')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exercises_estimation')),
    sa.UniqueConstraint('exercise_id', name=op.f('uq_exercises_estimation_exercise_id'))
    )
    op.create_table('exercises_image',
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('image_label', sa.String(length=300), nullable=False),
    sa.Column('image_color', sa.String(length=20), nullable=False),
    sa.Column('options', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('correct_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('fk_exercises_image_exercise_id_exercises')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exercises_image')),
    sa.UniqueConstraint('exercise_id', name=op.f('uq_exercises_image_exercise_id'))
    )
    op.create_table('exercises_map_config',
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('map_region', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('fk_exercises_map_config_exercise_id_exercises')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exercises_map_config')),
    sa.UniqueConstraint('exercise_id', name=op.f('uq_exercises_map_config_exercise_id'))
    )
    op.create_table('exercises_map_hotspots',
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('hotspot_key', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('fk_exercises_map_hotspots_exercise_id_exercises')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exercises_map_hotspots'))
    )
    op.create_table('exercises_match_pairs',
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('left_text', sa.String(length=300), nullable=False),
    sa.Column('right_text', sa.String(length=300), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('fk_exercises_match_pairs_exercise_id_exercises')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exercises_match_pairs'))
    )
    op.create_table('exercises_multiple_choice',
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('options', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('correct_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('fk_exercises_multiple_choice_exercise_id_exercises')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exercises_multiple_choice')),
    sa.UniqueConstraint('exercise_id', name=op.f('uq_exercises_multiple_choice_exercise_id'))
    )
    op.create_table('exercises_true_false',
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('fk_exercises_true_false_exercise_id_exercises')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exercises_true_false')),
    sa.UniqueConstraint('exercise_id', name=op.f('uq_exercises_true_false_exercise_id'))
    )
    op.create_table('answers_chronological',
    sa.Column('answer_id', sa.UUID(), nullable=False),
    sa.Column('submitted_order', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], name=op.f('fk_answers_chronological_answer_id_answers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_answers_chronological')),
    sa.UniqueConstraint('answer_id', name=op.f('uq_answers_chronological_answer_id'))
    )
    op.create_table('answers_estimation',
    sa.Column('answer_id', sa.UUID(), nullable=False),
    sa.Column('submitted_value', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], name=op.f('fk_answers_estimation_answer_id_answers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_answers_estimation')),
    sa.UniqueConstraint('answer_id', name=op.f('uq_answers_estimation_answer_id'))
    )
    op.create_table('answers_image',
    sa.Column('answer_id', sa.UUID(), nullable=False),
    sa.Column('picked_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], name=op.f('fk_answers_image_answer_id_answers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_answers_image')),
    sa.UniqueConstraint('answer_id', name=op.f('uq_answers_image_answer_id'))
    )
    op.create_table('answers_map_click',
    sa.Column('answer_id', sa.UUID(), nullable=False),
    sa.Column('picked_hotspot_key', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], name=op.f('fk_answers_map_click_answer_id_answers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_answers_map_click')),
    sa.UniqueConstraint('answer_id', name=op.f('uq_answers_map_click_answer_id'))
    )
    op.create_table('answers_match',
    sa.Column('answer_id', sa.UUID(), nullable=False),
    sa.Column('left_indices', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('right_indices', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], name=op.f('fk_answers_match_answer_id_answers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_answers_match')),
    sa.UniqueConstraint('answer_id', name=op.f('uq_answers_match_answer_id'))
    )
    op.create_table('answers_multiple_choice',
    sa.Column('answer_id', sa.UUID(), nullable=False),
    sa.Column('picked_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], name=op.f('fk_answers_multiple_choice_answer_id_answers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_answers_multiple_choice')),
    sa.UniqueConstraint('answer_id', name=op.f('uq_answers_multiple_choice_answer_id'))
    )
    op.create_table('answers_true_false',
    sa.Column('answer_id', sa.UUID(), nullable=False),
    sa.Column('picked_value', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], name=op.f('fk_answers_true_false_answer_id_answers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_answers_true_false')),
    sa.UniqueConstraint('answer_id', name=op.f('uq_answers_true_false_answer_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answers_true_false')
    op.drop_table('answers_multiple_choice')
    op.drop_table('answers_match')
    op.drop_table('answers_map_click')
    op.drop_table('answers_image')
    op.drop_table('answers_estimation')
    op.drop_table('answers_chronological')
    op.drop_table('exercises_true_false')
    op.drop_table('exercises_multiple_choice')
    op.drop_table('exercises_match_pairs')
    op.drop_table('exercises_map_hotspots')
    op.drop_table('exercises_map_config')
    op.drop_table('exercises_image')
    op.drop_table('exercises_estimation')
    op.drop_table('exercises_chrono_items')
    op.drop_table('answers')
    op.drop_table('sessions')
    op.drop_table('exercises')
    op.drop_table('subtopics')
    op.drop_table('topics')
    op.drop_table('users')
    op.drop_table('categories')
    # ### end Alembic commands ###
